### ISSUE TITLE
Analyze whole TeXLive

### ISSUE THREAD

**Issue by koppor** [koppor/errorformat-to-html#3]
Initial idea:

```yaml
jobs:
  copy-tex-lua:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Start Container
        run: |
          # Create and start the container
          CONTAINER_ID=$(docker create registry.gitlab.com/islandoftex/images/texlive:latest)
          
          # Find all .tex and .lua files
          FILES=$(docker run --rm registry.gitlab.com/islandoftex/images/texlive:latest find / -type f \( -name "*.tex" -o -name "*.lua" \))

          # Copy each file while preserving structure
          for FILE in $FILES; do
            TARGET_PATH="/tmp${FILE%/*}"  # Extract directory structure
            mkdir -p "$TARGET_PATH"        # Ensure the target directory exists
            docker cp "$CONTAINER_ID:$FILE" "$TARGET_PATH/"
          done

          # Clean up
          docker rm -f $CONTAINER_ID
```

**Comment by Witiko** [comment]
> `# Create and start the container`

Would it make sense to run the whole workflow in a `texlive/texlive` container?

For example:

``` yaml
name: Generate GitHub page
env:
  LUAINPUTS: expltools/explcheck/src
jobs:
  check-and-publish:
    container: texlive/texlive:latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        find /usr/local/texlive/ -iregex ".*\.\(tex\|sty\|cls\|opt\)$" -exec \
        texlua expltools/explcheck/src/explcheck.lua --porcelain {} + > errors.txt
```

Note that explcheck currently assumes that all files are in expl3. Therefore, analyzing the entire TeX Live will produce many false positives. This is OK for the purpose of a demonstration / proof of concept: if the website looks and operates well with more warnings/errors than expected, then it will also look and operate well with the expected workload. However, a solution to https://github.com/Witiko/expltools/issues/32 would need to either pre-filter the files, as shown on pages 35 and 36 of my [presentation slides][1] from the 2024 general assembly of CSTUG, or wait until https://github.com/Witiko/expltools/issues/38 is closed.

<details>

Going forward, there is also a question of configuration to be considered. Different expl3 files may need different explcheck config files to prevent false positive warnings and errors. We could solve this by having a .csv file similar to [`l3prefixes.csv`](https://github.com/latex3/latex3/blob/main/l3kernel/doc/l3prefixes.csv) in the repository, where authors would add URLs of config files. Then, we would use these config files during the website generation. However, this still isn't ideal, since it requires cooperation with authors and URLs will become outdated and require maintenance. Ideally, we would _know_ where to find the config file for a given expl3 file and the config files would be part of TeX Live. However, I am not sure how to get to that point.

</details>

Note also that even after https://github.com/Witiko/expltools/issues/38 is closed, non-expl3 files will still produce warning W100 (no standard delimiters). Therefore, while the "errorformat" output of `explcheck --porcelain` may be suitable for a demonstration / proof of concept, a solution to https://github.com/Witiko/expltools/issues/32 should likely use [the Lua interfaces of explcheck][2] directly instead of the "errorformat" output. This way, after https://github.com/Witiko/expltools/issues/38 has been closed, we can determine whether a file is in expl3 or not by looking at the list of expl3 ranges produced by the preprocessing step.

 [1]: https://www.cstug.cz/informace/zpravy/2024-11-18-valna-hromada-2024/files/starynovotny-expltools-slides.pdf
 [2]: https://github.com/Witiko/expltools#usage
